version: "2"
services:
  app:
    build: ./app
    links:
      - db
    ports:
      - "5000:5000"
    labels:
      kompose.service.type: LoadBalancer

  db:
    image: mysql:5.7
    ports:
      - "32000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql-data-volume:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    labels:
      kompose.service.type: LoadBalancer

volumes:
  mysql-data-volume: {}