version: "2"
services:
  app:
    image: glechner99/flask-app
    build: ./app
    links:
      - db
    ports:
      - "5000:5000"
    labels:
      kompose.service.type: LoadBalancer

  db:
    image: mysql:5.7
    ports:
      - "32000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumeMounts:
      - name: mysql-data-volume
        mountPath: /var/lib/mysql
      - name: mysql-init-script
        mountPath: /docker-entrypoint-initdb.d/init.sql
        subPath: init.sql
    labels:
      kompose.service.type: LoadBalancer

volumes:
  mysql-data-volume:
    persistentVolumeClaim:
      claimName: mysql-data-claim
    

