apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-init-script
data:
  init.sql: |
    CREATE DATABASE IF NOT EXISTS dbproyecto;
    USE dbproyecto;


    CREATE TABLE participantes (
      NOMBRE_ALUMNO VARCHAR(50),
      CARRERA VARCHAR(50)
    );

    INSERT INTO participantes
      (NOMBRE_ALUMNO, CARRERA)
    VALUES
      ('Sebastian S. Bertani', 'Ingenieria'),
      ('German A. Lechner', 'Ingenieria');